import {
  SiAnthropic,
  SiApachekafka,
  SiBun,
  SiCursor,
  SiDocker,
  SiDotnet,
  SiExpress,
  SiFigma,
  SiGit,
  SiGithub,
  SiGo,
  SiJavascript,
  SiKubernetes,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiNumpy,
  SiOpenjdk,
  SiPandas,
  SiPostgresql,
  SiPostman,
  SiPython,
  SiPytorch,
  SiRadixui,
  SiReact,
  SiRedis,
  SiRust,
  SiScikitlearn,
  SiShadcnui,
  SiSharp,
  SiSocketdotio,
  SiSpringboot,
  SiSwagger,
  SiTailwindcss,
  SiTensorflow,
  SiTerraform,
  SiTypescript,
  SiVercel,
} from "@icons-pack/react-simple-icons"
import type { IconType } from "@icons-pack/react-simple-icons"

/**
 * Map of `iconKey` (used in `data/stack.json` category items) to a
 * Simple-Icons React component. Add new technologies here — lookup is
 * by `simpleicons.org` slug (lowercased, no spaces or dots).
 *
 * NOTE: trademarked brands (AWS, Microsoft Azure) are intentionally NOT
 * in `@icons-pack/react-simple-icons`. List those technologies in
 * `data/stack.json` without an `iconKey` — the chip renders without an
 * icon, which is fine.
 */
export const STACK_ICON_REGISTRY: Record<string, IconType> = {
  typescript: SiTypescript,
  javascript: SiJavascript,
  python: SiPython,
  go: SiGo,
  rust: SiRust,
  csharp: SiSharp,
  dotnet: SiDotnet,
  springboot: SiSpringboot,
  openjdk: SiOpenjdk,
  react: SiReact,
  nextdotjs: SiNextdotjs,
  tailwindcss: SiTailwindcss,
  shadcnui: SiShadcnui,
  radixui: SiRadixui,
  nodedotjs: SiNodedotjs,
  bun: SiBun,
  postgresql: SiPostgresql,
  mongodb: SiMongodb,
  mysql: SiMysql,
  redis: SiRedis,
  apachekafka: SiApachekafka,
  docker: SiDocker,
  kubernetes: SiKubernetes,
  terraform: SiTerraform,
  anthropic: SiAnthropic,
  cursor: SiCursor,
  git: SiGit,
  github: SiGithub,
  figma: SiFigma,
  vercel: SiVercel,
  tensorflow: SiTensorflow,
  scikitlearn: SiScikitlearn,
  express: SiExpress,
  socketdotio: SiSocketdotio,
  postman: SiPostman,
  swagger: SiSwagger,
  pandas: SiPandas,
  numpy: SiNumpy,
  pytorch: SiPytorch,
}
